newrelic/newrelic-telemetry-sdk-python

azure-pipelines.yml, setup.cfg
Python 3.8 has been [released](https://www.python.org/dev/peps/pep-0569/)! This PR adds classifiers and testing for Python 3.8 where applicable.
Note: windows testing for python 3.8 is [not yet available](https://github.com/microsoft/azure-pipelines-image-generation/blob/1ffbeeee58fc9a1914be9af4091979ca4a06f685/images/win/Vs2019-Server2019-Readme.md).
=> Add python 3.8 support.

src/newrelic_telemetry_sdk/metric.py, tests/test_metric.py
The default values provided in the metric class init aren't particularly helpful, especially considering that `SummaryMetric` has invalid infinity / -infinity default values for min and max respectively.
This PR makes the values for `CountMetric` and `SummaryMetric` required inputs.
=> Remove metric defaults.

README.rst, THIRD_PARTY_NOTICES.rst, docs/api.rst, docs/conf.py, docs/index.rst, setup.py, src/newrelic_telemetry_sdk/__init__.py, src/newrelic_telemetry_sdk/client.py, tests/test_client.py
Note, this will force a bump to version 0.2
Python's [requests](https://github.com/psf/requests) library introduces a lot of dependencies that aren't necessarily used ([chardet](https://github.com/chardet/chardet) for example).
In order to reduce our dependency list (as well as the LGPL chardet dependency), this PR switches over to using pure `urllib3` calls.
This PR introduces a new `HTTPResponse` object that maintains _some_ compatibility with [requests](https://github.com/psf/requests).
* `json()`: returns a dictionary containing the json loaded response payload
* `raise_for_status()`: raises an `HTTPError` when the response is unsuccessful
* `status_code` has moved to `status`
* `ok`: returns True if the response status is in the range [200, 300)
* The `text` property is not …
=> Transition to urllib3.

src/newrelic_telemetry_sdk/client.py
This PR allows for exporters to override the pool class for the purposes of directing the traffic towards another network endpoint for testing and validation. This attribute should not be used or overridden in normal usage of the telemetry SDK.
=> Add an overridable pool class attribute for testability.

src/newrelic_telemetry_sdk/metric.py, src/newrelic_telemetry_sdk/span.py, tests/test_metric.py, tests/test_span.py
Tags can be provided as a custom mapping class. These custom mapping classes may not be mutable and they may not support all keys.
Any mapping provided should be converted into dict types for internal representation on a span or metric.
=> Ensure tags are of type dict on spans / metrics.

docs/advanced.rst, docs/api.rst, docs/index.rst, src/newrelic_telemetry_sdk/__init__.py, src/newrelic_telemetry_sdk/harvester.py, src/newrelic_telemetry_sdk/metric_batch.py, src/newrelic_telemetry_sdk/span_batch.py, tests/test_harvester.py, tests/test_metric_batch.py, tests/test_span_batch.py
This PR includes `Batch` and `Harvester` components that can be used to simplify aggregation, batching, and periodically sending to New Relic.
Batches provide a standard interface for aggregating and flushing data across different data types. This interface is used by the `Harvester` to forward data from batches to a client.
Documentation has been updated describing how to use these components.
=> Add batch and harvester components.

src/newrelic_telemetry_sdk/metric_batch.py, src/newrelic_telemetry_sdk/span_batch.py, tests/test_metric.py, tests/test_metric_batch.py, tests/test_span.py, tests/test_span_batch.py, tests/utils.py
Using a custom mapping class without a copy method for tags within batches resulted in a crash. Custom mapping classes are now properly converted to a dict for internal use by batches in the New Relic Python SDK.
=> Batch tags without a copy method raise an AttributeError.

README.rst, docs/advanced.rst, docs/api.rst, docs/index.rst, docs/quickstart.rst, src/newrelic_telemetry_sdk/__init__.py, src/newrelic_telemetry_sdk/batch.py, src/newrelic_telemetry_sdk/client.py, src/newrelic_telemetry_sdk/event.py, tests/test_batch.py, tests/test_client.py, tests/test_event.py
This PR implements custom event types, as requested in #13 .
Within this PR are:
* Client/Batch types for Events
* Documentation updates showcasing the event functionality (including docstrings and examples)
* Testing and verification for event behavior (including support for common tags/custom attributes in batches, which currently has no backend support)
=> Add support for event types.

src/newrelic_telemetry_sdk/client.py, tests/test_client.py
The SDK should transition to always using gzip compression for payloads rather than making it configurable.
=> Deprecate use of compression_threshold.

src/newrelic_telemetry_sdk/client.py, tests/test_client.py
Remove the deprecated `compression_threshold` argument. `gzip` compression is now enabled for all payloads, regardless of size.
=> Remove compression_threshold.

src/newrelic_telemetry_sdk/client.py, tests/test_client.py
Allow users to override the port for `SpanClient`, `EventClient`, and `MetricClient`.
```python
import os
import time
from newrelic_telemetry_sdk import Span, SpanClient
with Span(name='sleep') as span:
time.sleep(0.5)
span_client = SpanClient(os.environ['NEW_RELIC_INSERT_KEY'], port=8000)
response = span_client.send(span)
response.raise_for_status()
print('Span sleep sent successfully!')
```
=> Add port override.

src/newrelic_telemetry_sdk/harvester.py, tests/test_harvester.py
Fixes a crash when using the harvester with `EventClient`/`EventBatch`. See #23 for details.
=> Fix harvester crash when using event client.

src/newrelic_telemetry_sdk/client.py, tests/test_client.py
This PR adds a `Client.close` interface, allowing for connections to be explicitly closed before the client is disposed of.
=> Add a close interface for clients.

src/newrelic_telemetry_sdk/harvester.py, src/newrelic_telemetry_sdk/metric.py, src/newrelic_telemetry_sdk/metric_batch.py, tests/test_harvester.py, tests/test_metric.py, tests/test_metric_batch.py
There are a couple of proposed interface changes to be made. Prior to changing those interfaces, we must add deprecation warnings for those interfaces.
Overview of changes:
* Metric.from_value is removed, replaced with metric constructor
* CountMetric / SummaryMetric interval_ms must be specified
* Harvester.record is removed and replaced with Harvester.batch.record (or simply Batch.record)
* MetricBatch.record method is removed, replaced with MetricBatch.record_gauge, MetricBatch.record_count, MetricBatch.record_summary
=> Add deprecation warnings for removed interfaces.

docs/advanced.rst, src/newrelic_telemetry_sdk/harvester.py, src/newrelic_telemetry_sdk/metric_batch.py, tests/test_harvester.py, tests/test_metric_batch.py
This PR updates the metric batch interfaces to use individual `record_*` methods for each metric type. The reason for this is to support aggregation of metric "values" rather than actual complete metric objects.
The original thought process for having a unified `record` interface for batches was so that batch flush and client send could happen on the same thread to avoid a lock. Since we have made batches thread safe, it's no longer necessary to keep the batch interfaces uniform.
By allowing for separate interfaces for metric batches, the aggregations being done are more explicit, and in the case of `GaugeMetric`, more correct.
=> Update metric batch interface.

src/newrelic_telemetry_sdk/harvester.py, tests/test_harvester.py
This PR makes the client attribute on the `Harvester` class public since the `Harvester.batch` is also public.
This will allow users to manually flush data from the batch to the client immediately for use cases that require data to immediately be sent.
=> Make client public on the harvester.

docs/index.rst, docs/proxy.rst, setup.py, src/newrelic_telemetry_sdk/client.py, tests/test_client_proxy.py
This PR adds support for sending data to Newrelic via a proxy.
Closes: #17
=> Add proxy support.

src/newrelic_telemetry_sdk/client.py, tests/test_client.py
The x-request-id header is a uuid4 value that may be used by ingest in the future.
See newrelic/newrelic-telemetry-sdk-specs#17 for details.
=> Add x-request-id header to all requests.

src/newrelic_telemetry_sdk/client.py
I often face the problem when sending a New Relic event from a Databricks notebook that the request does not time out.
I would like to add the `timeout` parameter so it can fail faster and I can implement retries in my code.
Please let me know if there's something missing in my PR and any feedback is welcome!
Thank you!
=> Add timeout

.github/workflows/deploy.yml, .github/workflows/tests.yml, setup.cfg, tox.ini
Python 2.7 [support was dropped](https://github.com/actions/setup-python/issues/672) on June 19th. This solution is a TEMPORARY one that disables python 2.7 and pypy2 testing until a more permanent fix is implemented.
=> Remove py2.7

.github/workflows/tests.yml, setup.cfg, tox.ini
This PR removes Python 3.6 and adds Python 3.11 to match the Python versions supported in the newrelic-python-agent
=> Update python versions supported and tested

.github/workflows/tests.yml, docs/conf.py, setup.cfg, tox.ini
* Add classifiers for Python 3.12
* Add tests for Python 3.12
* Update pypy3.9 to pypy3.10
* Update sphinx to v7
* Update sphinx config to work with v7
* [Relevant docs](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping)
=> Misc Updates

src/newrelic_telemetry_sdk/client.py, tests/test_client.py, tests/test_client_proxy.py
After https://github.com/newrelic/newrelic-telemetry-sdk-python/pull/72 was merged the `newrelic-telemetry-sdk` still does not work properly with `urllib3` v2.
___NOTE:__ https://github.com/newrelic/newrelic-telemetry-sdk-python/pull/72 was not merged into `main` but into [`develop-urllib3-v2`](https://github.com/newrelic/newrelic-telemetry-sdk-python/tree/develop-urllib3-v2)._
The issue is that in urllib3 v2, the `ResponseCls` class attribute was removed from the `HTTPSConnectionPool` class:
- https://github.com/urllib3/urllib3/issues/2648
We were depending on `ResponseCls` to cause `urllib3` to return our custom `HTTPResponse` wrapper (which has extra methods like `ok` and `json()` methods).
As a workaround that is fully backwards compatible (and works with both `urllib3` v1 and v2), I …
=> Fix ResponseCls no longer existing on HTTPSConnectionPool

.github/workflows/deploy.yml
* Add build provenance to GitHub alongside PyPi.
=> Add Build Provenance to GitHub

.github/workflows/deploy.yml
Copy of https://github.com/newrelic/newrelic-python-agent/pull/1476 for this repo.
* Specify file extensions of artifacts to attest on deploy to remove attestations of attestations.
* See [example](https://github.com/newrelic/newrelic-python-agent/attestations/9684065) where there are attestations for `.publish.attestation` files. These are attestations for PyPI and should not be included.
=> More Specific Attestation List
